name: CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Cache make init results
      uses: actions/cache@v2
      with:
        path: |
          webapp/sql/dump.sql
          benchmarker/userdata/img
        key: ${{ runner.os }}-make-init-${{ hashFiles('Makefile')}}
        restore-keys: |
          ${{ runner.os }}-make-init-

    - name: Initialize the project
      run: make init

    - name: Start the server
      run: |
        cd webapp
        docker compose up -d

    - name: Run the benchmark
      run: |
        cd benchmarker
        docker build -t private-isu-benchmarker .
        docker run --network host --add-host host.docker.internal:host-gateway -i private-isu-benchmarker /opt/go/bin/benchmarker -t http://host.docker.internal -u /opt/go/userdata
